### ISSUE TITLE
each element in list of batch should be of equal size

### ISSUE THREAD

**Issue by ZhaoChenxi-nku** [jiuntian/interactdiffusion#14]
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/ubuntu16/zcx/HOI/interactdiffusion/trainer.py", line 104, in wrap_loader
    for batch in loader:  # TODO: it seems each time you have the same order for all epoch??
  File "/home/ubuntu16/anaconda3/envs/hoi/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 633, in __next__
    data = self._next_data()
  File "/home/ubuntu16/anaconda3/envs/hoi/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1345, in _next_data
    return self._process_data(data)
  File "/home/ubuntu16/anaconda3/envs/hoi/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1371, in _process_data
    data.reraise()
  File "/home/ubuntu16/anaconda3/envs/hoi/lib/python3.8/site-packages/torch/_utils.py", line 644, in reraise
    raise exception
RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/ubuntu16/anaconda3/envs/hoi/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/ubuntu16/anaconda3/envs/hoi/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 54, in fetch
    return self.collate_fn(data)
  File "/home/ubuntu16/anaconda3/envs/hoi/lib/python3.8/site-packages/torch/utils/data/_utils/collate.py", line 265, in default_collate
    return collate(batch, collate_fn_map=default_collate_fn_map)
  File "/home/ubuntu16/anaconda3/envs/hoi/lib/python3.8/site-packages/torch/utils/data/_utils/collate.py", line 127, in collate
    return elem_type({key: collate([d[key] for d in batch], collate_fn_map=collate_fn_map) for key in elem})
  File "/home/ubuntu16/anaconda3/envs/hoi/lib/python3.8/site-packages/torch/utils/data/_utils/collate.py", line 127, in <dictcomp>
    return elem_type({key: collate([d[key] for d in batch], collate_fn_map=collate_fn_map) for key in elem})
  File "/home/ubuntu16/anaconda3/envs/hoi/lib/python3.8/site-packages/torch/utils/data/_utils/collate.py", line 138, in collate
    raise RuntimeError('each element in list of batch should be of equal size')
RuntimeError: each element in list of batch should be of equal size

**Comment by zhaochenxi515** [comment]
when I set batch_size more than 1, it will cause this problem
